
# Config for CircleCI


version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-browsers-legacy

    working_directory: ~/repo

    environment: Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn install -DskipTests

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests! and gen code coverage
      - run: mvn integration-test
#      - run: mvn integration-test cobertura:cobertura
#
#      - store_test_results:
#            path: target/surefire-reports
#
#      - run:
#          name: Send to CodeCov
#          command: bash <(curl -s https://codecov.io/bash)